### ISSUE TITLE
Implement geometries

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer-fiber#19]
- [ ]     BoxBufferGeometry
- [ ]     BoxGeometry
- [ ]     CircleBufferGeometry
- [ ]     CircleGeometry
- [ ]     ConeBufferGeometry
- [ ]     ConeGeometry
- [ ]     CylinderBufferGeometry
- [ ]     CylinderGeometry
- [ ]     DodecahedronBufferGeometry
- [ ]     DodecahedronGeometry
- [ ]     EdgesGeometry
- [ ]     ExtrudeGeometry
- [ ]     ExtrudeBufferGeometry
- [ ]     IcosahedronBufferGeometry
- [ ]     IcosahedronGeometry
- [ ]     LatheBufferGeometry
- [ ]     LatheGeometry
- [ ]     OctahedronBufferGeometry
- [ ]     OctahedronGeometry
- [ ]     ParametricBufferGeometry
- [ ]     ParametricGeometry
- [ ]     PlaneBufferGeometry
- [ ]     PlaneGeometry
- [ ]     PolyhedronBufferGeometry
- [ ]     PolyhedronGeometry
- [ ]     RingBufferGeometry
- [ ]     RingGeometry
- [ ]     ShapeBufferGeometry
- [ ]     ShapeGeometry
- [ ]     SphereBufferGeometry
- [ ]     SphereGeometry
- [ ]     TetrahedronBufferGeometry
- [ ]     TetrahedronGeometry
- [ ]     TextBufferGeometry
- [ ]     TextGeometry
- [ ]     TorusBufferGeometry
- [ ]     TorusGeometry
- [ ]     TorusKnotBufferGeometry
- [ ]     TorusKnotGeometry
- [ ]     TubeGeometry
- [ ]     TubeBufferGeometry
- [ ]     WireframeGeometry

**Comment by johnmarinelli** [comment]
Hey, I've added a trivial SphereGeometry descriptor here: https://github.com/johnmarinelli/react-three-renderer-fiber/blob/71ee9408fee87c612ed911dd82c132996458d48a/src/core/hostDescriptors/descriptors/geometries/sphereGeometry.ts

let me know how this looks.  I basically copied the template from boxGeometry and replaced it with Sphere's attributes.  If this looks alright then I'll go ahead and do it with all the other geometries, seems like a good starting point to start contributing.  Unless, do you have a method of automatically pulling from THREE.js's exports and creating descriptors that way?

**Comment by toxicFork** [comment]
Yes :D
