### ISSUE TITLE
Allow normal browsers to be used for tests

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer-fiber#23]
See https://github.com/toxicFork/react-three-renderer-fiber/blob/6de6014aa11c015d6fc9d0a59d01c3a6e5161da5/tests/karma.conf.js#L26

Please change it so that it will check for "whatever browser you may have" and launch it in this order of preference of the author:

- Firefox Nightly
- Firefox
- Chrome
- Edge

**Comment by johnrees** [comment]
Can this be closed for now?

**Comment by toxicFork** [comment]
Oh yeah! Thanks :D
