### ISSUE TITLE
Branch off into "custom react renderer" framework

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer-fiber#32]
Because I really want to see react-convnetjs

Declarative all the things!

**Comment by sompylasar** [comment]
This?
https://github.com/facebook/react/tree/2c228f15a0aa862ad92876d0f426a8ade45f1576/packages/react-reconciler
https://www.npmjs.com/package/react-reconciler
https://unpkg.com/react-reconciler@0.2.0/

**Comment by johnrees** [comment]
Hmmm, this is pretty interesting actually. I'll try and help to get this stable first!
