### ISSUE TITLE
turn into npm package

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer-fiber#34]
- [x] reserve package name
- [ ] publish v0
Bonus points:
- [ ] make Travis detect and push version tags into npm automatically

**Comment by toxicFork** [comment]
- [ ] move non library code into examples directory

**Comment by toxicFork** [comment]
https://www.npmjs.com/package/react-three-renderer-fiber I'm going to bet it won't work at all

Well at least the package name is reserved

I'm thinking of either keeping the fiber version as a separate package

Or creating a new major version for `react-three-renderer` instead and deprecating this one, once a v1 is achieved

(I like the latter more)

**Comment by johnrees** [comment]
:+1: for new major version

**Comment by nickpolet** [comment]
Yea I think a new major version would be best as well. Really cant wait until this is ready for use. Got a project that is tied into React 16 and would love to integrate r3r at some point. We're using too many React 16 functions to justify migrating backwards.

**Comment by dkadrios** [comment]
Has any progress been made on getting the package to work?  I've been messing around trying to add the library toa project either via npm or directly from github with little luck.  The first hurdle is that the entry point in package.json is `./lib/main.js`, while the actual built file is `./lib/index.js`.  Also it seems that `react-fiber-export` should be in "dependencies" and not "devDependencies".

Even with those fixes though I encounter "require.context is not a function" in `hostDescriptors/index.js` and I'm stuck.
