### ISSUE TITLE
.tsconfig is invalid?

### ISSUE THREAD

**Issue by johnmarinelli** [toxicFork/react-three-renderer-fiber#40]
Hi,

I was using react-three-renderer for a project of mine and am pretty excited about it so far.  I wanted to contribute and found this project and figured that this would be a better place to help out.

Unfortunately, when i run `yarn start` I get this error:
`ERROR in [at-loader] TS5053: Option 'allowJs' cannot be specified with option 'declaration'.`

```
~/Documents/js/react/react-three-renderer-fiber master Ƭ̵̬̊  yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.93s.
~/Documents/js/react/react-three-renderer-fiber master Ƭ̵̬̊  yarn start
yarn run v1.3.2
$ webpack-dev-server --config ./examples/webpack.config.js --content-base examples/
Project is running at http://localhost:8080/
webpack output is served from /dist/
Content not from webpack is served from /Local/Users/john/Documents/js/react/react-three-renderer-fiber/examples

[at-loader] Using typescript@2.5.3 from typescript and "tsconfig.json" from /Local/Users/john/Documents/js/react/react-three-renderer-fiber/examples/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
Hash: a3c6ddf2e9784ee7a997
Version: webpack 3.7.1
Time: 10963ms
    Asset     Size  Chunks                    Chunk Names
bundle.js  4.95 MB       0  [emitted]  [big]  main
   [3] ./node_modules/three/build/three.module.js 1.01 MB {0} [built]
  [78] multi (webpack)-dev-server/client?http://localhost:8080 ./examples/src/index.tsx 40 bytes {0} [built]
  [79] (webpack)-dev-server/client?http://localhost:8080 7.23 kB {0} [built]
  [80] ./node_modules/url/url.js 23.3 kB {0} [built]
  [86] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [88] ./node_modules/loglevel/lib/loglevel.js 7.74 kB {0} [built]
  [89] (webpack)-dev-server/client/socket.js 1.04 kB {0} [built]
 [121] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
 [123] ./node_modules/html-entities/index.js 231 bytes {0} [built]
 [126] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [127] (webpack)/hot/log.js 1.04 kB {0} [optional] [built]
 [128] (webpack)/hot/emitter.js 77 bytes {0} [built]
 [130] ./examples/src/index.tsx 2.34 kB {0} [built]
 [131] ./src/index.ts 295 bytes {0} [built]
 [132] ./src/bridge/React3.tsx 5.69 kB {0} [built]
    + 178 hidden modules

ERROR in [at-loader] TS5053: Option 'allowJs' cannot be specified with option 'declaration'.
webpack: Failed to compile.
```

Any ideas what's wrong?  I've tried permutations of true's and false's between `allowJs` and `declaration` to avail.  

It appears others have had the same problem but there hasn't been a clear fix - see https://github.com/Microsoft/TypeScript/issues/7546

**Comment by johnmarinelli** [comment]
So I just removed the "allowJs" option from the examples tsconfig file and it worked (sort of) - see here:

https://github.com/johnmarinelli/react-three-renderer-fiber/commit/48f87479cc15aea6fab4725a353e88c8ba84c23a#diff-d220dfbe875f6dd8ffd08c546901c18e

After that, I got some compile time errors about some objects not being assignable to undefined, which I fixed by adding default values of empty objects heh...

https://github.com/johnmarinelli/react-three-renderer-fiber/commit/48f87479cc15aea6fab4725a353e88c8ba84c23a#diff-2e609f6d2e95641822f07895228ae886

https://github.com/johnmarinelli/react-three-renderer-fiber/commit/48f87479cc15aea6fab4725a353e88c8ba84c23a#diff-7dad78df03d7ac3cbce7cac51a4aec90

So yeah.  It compiles for me now, hope to contribute soon

**Comment by toxicFork** [comment]
Apologies for the late response, I have been away for a bit. Happy to hear it worked for you, I will check if anything like that needs to be done still, it may be due to package version or platform differences. Looking forward to your contributions :)
